# 1. Create a 3x3x3 array with random values 

In [10]:
from numpy import array
import numpy as np
arr=np.empty((3,3,3))
arr1=np.random.randn(3,3,3)
print(arr,"\n")
print(arr1)

[[[1.22461926 0.0430489  0.92523077]
  [2.04882013 0.4012677  0.19070389]
  [1.68695306 0.23475777 0.81528226]]

 [[0.96784173 0.63806655 0.78986859]
  [0.60864967 0.20364198 0.46922222]
  [0.2942867  0.46541379 0.16193522]]

 [[0.56294575 0.78053546 0.65671876]
  [0.30265834 0.20614384 0.34443407]
  [1.45526394 0.92964391 0.7981744 ]]] 

[[[-2.85402932 -0.15470356 -0.77538044]
  [-0.61105716  1.20896367  0.45079516]
  [ 1.38937869  1.67763354 -1.01329086]]

 [[-1.25170242  0.24747523  2.12708518]
  [-0.65244807  1.68489065  0.72951656]
  [-0.46728629  0.75279279 -2.43441497]]

 [[-1.11384146 -1.12839621  1.5602834 ]
  [-0.81836988 -0.38649951  0.74505086]
  [ 0.57482109  0.86417212  0.12136599]]]


# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [25]:
arr1 = np.eye(5,5)
for i in range(1,5):
    arr1[i,i-1]=i
print(arr1)

[[1. 0. 0. 0. 0.]
 [1. 1. 0. 0. 0.]
 [0. 2. 1. 0. 0.]
 [0. 0. 3. 1. 0.]
 [0. 0. 0. 4. 1.]]


# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [31]:
arr = np.eye(8,8)
l1=[1,0,1,0,1,0,1,0]
l2=[0,1,0,1,0,1,0,1]
for i in range(8):
    if i%2==0:
        arr[i]=l1
    else:
        arr[i]=l2
print(arr)
        


[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


# 4. Normalize a 5x5 random matrix

In [41]:
arr=np.random.randn(5,5)
print(arr)
a=np.linalg.det(arr)
print(arr/a)


[[ 0.92845659  1.96304862  0.11727903 -0.35958399  1.37109406]
 [ 1.10984029 -0.9003322   0.94722238  0.48246194 -0.13086597]
 [-0.21920646 -0.31296006  1.558597    1.02028951  0.58822919]
 [ 0.17724552 -1.54675111  0.62239496  0.9335346   0.26098789]
 [-0.16930208 -0.40616491 -1.71598597 -1.43628578 -0.15802345]]
[[-0.21930348 -0.46367639 -0.02770156  0.08493453 -0.32385543]
 [-0.26214671  0.21266044 -0.22373601 -0.11395857  0.03091083]
 [ 0.05177705  0.07392185 -0.36814403 -0.24099462 -0.13894103]
 [-0.04186578  0.36534601 -0.14701106 -0.22050292 -0.06164591]
 [ 0.03998952  0.09593704  0.40531965  0.33925386  0.03732549]]


# 5.  How to find common values between two arrays?

In [44]:
arr1 = np.array([1,2,3,4,5,6])
arr2 = [2,3,4,8,9,7,0]
print("Common values between two arrays:")
print(np.intersect1d(arr1, arr2))

Common values between two arrays:
[2 3 4]


# 6.How to get the dates of yesterday, today and tomorrow?

In [42]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yestraday: ",yesterday)
today     = np.datetime64('today', 'D')
print("Today: ",today)
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow: ",tomorrow)

Yestraday:  2020-07-27
Today:  2020-07-28
Tomorrow:  2020-07-29


# 7. Consider two random array A and B, check if they are equal

In [54]:
arr = np.empty((5))
print(arr)
arr2 = np.empty((5))
print(arr2)
arrequal = np.allclose(arr, arr2)
print(arrequal)


[4.31881022 3.15286738 7.55834142 8.86515064 9.89620071]
[4.31881022 3.15286738 7.55834142 8.86515064 9.89620071]
True


# 8.Create random vector of size 10 and replace the maximum value by 0 

In [72]:
arr = np.random.random(15)
print(arr,"\n")
arr[arr.argmax()] = 0
print("Maximum value replaced by 0:")
print(arr)

[0.96340849 0.58662844 0.41662151 0.27490498 0.73072334 0.8799136
 0.15030713 0.10512106 0.51342198 0.51392457 0.21055178 0.05551186
 0.91940292 0.69370891 0.49206211] 

Maximum value replaced by 0:
[0.         0.58662844 0.41662151 0.27490498 0.73072334 0.8799136
 0.15030713 0.10512106 0.51342198 0.51392457 0.21055178 0.05551186
 0.91940292 0.69370891 0.49206211]


# 9. How to print all the values of an array?

In [61]:
a=np.empty((9))
print(a[:])

[1. 1. 1. 2. 1. 3. 1. 4. 1.]


# 10.Subtract the mean of each row of a matrix

In [73]:
arr1=np.random.rand(3,6)
Y = arr1 - arr1.mean(axis=1,keepdims=True)
print(Y)

[[ 0.43179577 -0.25285291  0.10959676 -0.27922469  0.24297529 -0.25229022]
 [-0.41141799 -0.28803657  0.13032369  0.34074156  0.38529399 -0.15690468]
 [ 0.05032188  0.5234476   0.05212295 -0.26677019 -0.40016293  0.04104069]]


# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [78]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
np.add.at(Z, I, 1)
print(Z)

[4. 1. 2. 4. 3. 2. 5. 5. 2. 2.]


# 12.How to get the diagonal of a dot product?

In [87]:
a = array([[1, 0], [0, 1]])
b = array([[4, 1], [2, 2]])
c=(np.dot(a, b))
print(c.diagonal())

[4 2]


# 13.How to find the most frequent value in an array?

In [88]:
x = np.random.randint(0, 10, 40)
print("Original array:")
print(x)
print("Most frequent value in the above array:")
print(np.bincount(x).argmax())

Original array:
[3 5 2 0 7 2 7 2 4 2 5 8 6 7 7 6 0 5 8 9 4 8 7 6 4 3 4 3 5 4 2 6 4 5 9 9 5
 5 6 1]
Most frequent value in the above array:
5


# 14.How to get the n largest values of an array

In [89]:
x = np.arange(10)
print("Original array:")
print(x)
np.random.shuffle(x)
n = 1
print (x[np.argsort(x)[-n:]])

Original array:
[0 1 2 3 4 5 6 7 8 9]
[9]


# 15.How to create a record array from a regular array?

In [91]:
a1=np.array([10, 42, 58, 70])
a2=np.array(['Rose','Lily','Lotus','Mogra'])
a3=np.array([12.20,15,20,40])
result= np.core.records.fromarrays([a1, a2, a3],names='a,b,c')
print(result[0])
print(result[1])
print(result[2])


(10, 'Rose', 12.2)
(42, 'Lily', 15.)
(58, 'Lotus', 20.)
